[package]
name = "hello_world"
type = "bin"
authors = [""]
compiler_version = ">=0.32.0"

[dependencies]
bignum = {tag = "v0.2", git = "https://github.com/noir-lang/noir-bignum/"}
bigcurve = {tag = "v0.1", git = "https://github.com/noir-lang/noir_bigcurve/"}